apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lucumt-system-$PRODUCT_PHASE
  name: lucumt-system-$PRODUCT_PHASE
  namespace: lucumt-project   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: lucumt-system-$PRODUCT_PHASE
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lucumt-system-$PRODUCT_PHASE
    spec:
      imagePullSecrets:
        - name: local-docker-hub
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/lucumt-system:$BUILD_TAG
          readinessProbe:
            httpGet:
              path: lucumt-system/actuator/health
              port: $NODE_PORT
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: lucumt-system-$PRODUCT_PHASE
          env:
            - name: DUBBO_IP_TO_REGISTRY
              value: $DUBBO_IP
          ports:
            - containerPort: $NODE_PORT
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lucumt-system-$PRODUCT_PHASE
  name: lucumt-system-$PRODUCT_PHASE
  namespace: lucumt-project
spec:
  ports:
    - name: http
      port: $NODE_PORT
      protocol: TCP
      targetPort: $NODE_PORT
      nodePort: $NODE_PORT
    - name: dubbo
      port: $DUBBO_PORT
      protocol: TCP
      targetPort: $DUBBO_PORT
      nodePort: $DUBBO_PORT
  selector:
    app: lucumt-system-$PRODUCT_PHASE
  sessionAffinity: None
  type: NodePort
